# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Wrong Abstraction
tagline:          Ruby Developer 
url:              http://vpfaulkner@github.io.com
paginate:         1
baseurl:          /
author:
  name:           Vance Faulkner
  url:            vpfaulkner@github.io.com 
  email:          vpfaulkner@gmail.com
encoding: UTF-8

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  About Me: '/about_me'
  Playbook: '/playbook'
  Archive: '/archive'
